name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Run specs
        run: bundle exec rspec
      - name: Run cops
        run: bundle exec rubocop

        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish to RubyGems
        uses: actionshub/publish-gem-to-rubygems@main
        with:
          api_key: ${{ secrets.RUBY_GEMS_API_KEY }}
